swagger: '2.0'
info:
  version: 1.0.0
  title: fastify-swagger
schemes:
  - http
  - https
paths:
  /v1/reviewAndRatings:
    post:
      tags:
        - Reviews & Rating
      parameters:
        - name: body
          in: body
          schema:
            type: object
            required:
              - entity
              - rating
              - author
            properties:
              entity:
                type: string
              author:
                type: number
              title:
                type: string
              reviewDesc:
                type: string
              rating:
                type: number
                maximum: 5
                minimum: 1
            additionalProp1Properties: false
      responses:
        '200':
          schema:
            type: object
            description: Success review created response
            properties:
              entity:
                type: string
              author:
                type: number
              title:
                type: string
              reviewDesc:
                type: string
              rating:
                type: number
                maximum: 5
                minimum: 1
              sentimentScore:
                type: string
              uuid:
                type: string
          description: Success review created response
    get:
      tags:
        - Reviews & Rating
      parameters:
        - type: string
          required: true
          name: entity_id
          in: query
        - type: string
          required: false
          name: limit
          in: query
        - type: string
          required: false
          name: offset
          in: query
        - type: string
          enum:
            - created_at
            - is_helpful
            - is_not_helpful
            - rating
          required: false
          name: sort_key
          in: query
        - type: string
          enum:
            - ASC
            - DESC
          required: false
          name: sort_order
          in: query
        - type: string
          maximum: 5
          minimum: 1
          required: false
          name: filterByRating
          in: query
      responses:
        '200':
          description: Default Response
  /v1/reviewAndRatings/updateReviewByUsersReaction:
    patch:
      tags:
        - Reviews & Rating
      parameters:
        - name: body
          in: body
          schema:
            type: object
            required:
              - reviewId
              - userReaction
            properties:
              reviewId:
                type: string
              userReaction:
                type: string
                enum:
                  - is_helpful
                  - is_not_helpful
      responses:
        '200':
          schema:
            type: object
            description: Succesfully updated user reaction to review
            properties:
              reviewId:
                type: string
              userReaction:
                type: string
                enum:
                  - is_helpful
                  - is_not_helpful
          description: Succesfully updated user reaction to review
  /v1/reviewAndRatings/reviewManually:
    patch:
      description: Used to manually review
      tags:
        - Reviews & Rating
      parameters:
        - name: body
          in: body
          schema:
            type: object
            required:
              - reviewId
              - approved
            properties:
              reviewId:
                type: string
              approved:
                type: boolean
      responses:
        '200':
          schema:
            type: object
            description: Manual review successful!
          description: Manual review successful!
  /v1/product:
    get:
      tags:
        - Product
      parameters:
        - type: string
          required: true
          name: product_id
          in: query
      responses:
        '200':
          schema:
            type: object
            description: Success product fetched
            properties:
              product_id:
                type: string
              name:
                type: string
              description:
                type: string
              price:
                type: string
              image:
                type: string
          description: Success product fetched
